### ISSUE TITLE
How to integrate the library in React project ?

### ISSUE THREAD

**Issue by avin3sh** [ScarletsFiction/SFMediaStream#1]
I need help regarding integrating the library in React, for client side and Node, for the server side. Is this library available on NPM ?

**Comment by StefansArya** [comment]
I suppose that you already find the answer. But because this was the first issue, I would like to answer it.

For the server side you can use `socket.io` to handle the socket connection, like the example below this line.
(you can use `express` or other HTTP library instead of `serberries`)
https://github.com/ScarletsFiction/SFMediaStream/blob/e9c43ccb79c7942fa9ad0c86b38bb328131244a6/example/StreamingTest/server.js#L32-L34

And for the client side, currently I write the library in Vanilla JS and haven't scale it up to React or TypeScript. So I'm not sure it would work perfectly on there.

Usually you would need to include the distributable file from `dist` folder with `<script>` tag and place it on HTML header or [bundle it with webpack](https://sdk.gooddata.com/gooddata-ui/docs/4.1.1/ht_use_react_components_with_vanilla_js.html)

Maybe I will put this library on NPM after everything ready.
