### ISSUE TITLE
Stream Delay

### ISSUE THREAD

**Issue by Tuner32** [ScarletsFiction/SFMediaStream#15]
I used example code 
startbtn.addEventListener('click', function () {

	var presenterMedia = new ScarletsMediaPresenter({
	    audio:{
				channelCount:1,
				echoCancellation: false
	    }
	}, 100);

	presenterMedia.onRecordingReady = function(packet){
	    console.log("Recording started!");
	    console.log("Header size: " + packet.data.size + "bytes");

	    // Every new streamer must receive this header packet
	    socket.emit('bufferHeader', packet);
	}

	presenterMedia.onBufferProcess = function(packet){
	    //console.log("Buffer sent: " + packet[0].size + "bytes");
	    socket.emit('bufferStream', packet);
	}

	presenterMedia.startRecording();

});
videoStreamer = new ScarletsAudioStreamer(null, 100);
videoStreamer.playStream();

// Buffer header must be received first
socket.on('bufferHeader', function(packet,socketid){
		videoStreamer.setBufferHeader(packet);
});

// Receive buffer and play it
socket.on('bufferstream', function(packet,socketid){
		videoStreamer.receiveBuffer(packet);
});
like this, but It keep make more delay If I keep use that

**Comment by StefansArya** [comment]
Hi!
Unfortunately when using `receiveBuffer` it would immediately appended into [MediaSource](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/addSourceBuffer)'s [SourceBuffer](https://developer.mozilla.org/en-US/docs/Web/API/SourceBuffer) and I'm not pretty sure what causes the delay. I think if the next buffer was late to be received by the streamer, the browser would automatically add a delay to avoid waiting for the next buffer.

For realtime stream the current solution is by replacing `receiveBuffer` with `realtimeBufferPlay`. The buffers would immediately played after receive it, but it may have some gap because the streamer need to wait for the buffer to be received from the network and decode it into playable media.

**Comment by Tuner32** [comment]
Thank you for answer, It was really useful for me. Can I ask you about How can I use receive audio data used by web audio api?

**Comment by Tuner32** [comment]
And dose it is possible to use this in nodejs?

**Comment by StefansArya** [comment]
If you want to receive audio data you will need to add a callback on `onRecordingReady` for getting the first media header and `onBufferProcess` for getting recorded buffers.
> The `presenterInstance` used in code below is created with `new ScarletsMediaPresenter()`.

https://github.com/ScarletsFiction/SFMediaStream/blob/c6707c9d60225509b253e51d38ffb98b1313ef4a/example/browser-to-server-speaker/browser/presenter.js#L79-L98

This library is for browser because Node.js doesn't natively support WebAudio API 😅. If you just want to play the stream on Node.js or save the buffers as a file there's [an example](https://github.com/ScarletsFiction/SFMediaStream/tree/v1/example/browser-to-server-speaker) for it.

But I think you can use this library on Node.js with [Puppeteer ](https://github.com/puppeteer/puppeteer/)to spawn headless/windowless Chrome, but it could get complicated. Depends on your project's requirement maybe you can use **WebRTC** for realtime communication or **FFMPEG** for broadcasting audio.

**Comment by Tuner32** [comment]
Thank you but I can't understand some code about decoded and opus codec, Can I ask you to use discord? or any cheating app.

**Comment by StefansArya** [comment]
You're welcome, but sorry currently I'm not available for private chat. I will try to help if I have time and know how to answer.

If you prefer to use `wav` instead of `opus` codec you can specify `mimeType` only from the presenter. The streamer will automatically follow the mimeType after received the first `bufferHeader`.
```js
let presenter = new ScarletsMediaPresenter({
	mimeType: 'audio/wav',
    audio:{
        channelCount:2,
        sampleRate:48000,
        echoCancellation: false
    }
}, 100);
```
---

In case if the browser doesn't support some codec like `audio/wav`, `audio/webm`, or `audio/ogg` you need to add the [polyfill](https://www.npmjs.com/package/opus-media-recorder#why-opus-media-recorder) before using the library.

https://github.com/ScarletsFiction/SFMediaStream/blob/c6707c9d60225509b253e51d38ffb98b1313ef4a/example/browser-to-server-speaker/index.html#L19-L27

You will also need to add this somewhere in your code.
```js
window.MediaRecorder = OpusMediaRecorder;
```
---

In case if you want to convert the media file (`.ogg`, `.webm`, `.wav`) that was saved on the server, you can use [fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg).

**Comment by Tuner32** [comment]
Actually  I want receive mic on nodejs and mix and effect use https://github.com/audiojs/web-audio-api this  and stream again. Dose it is possible? How can I receive data and connect with web audio api?

**Comment by StefansArya** [comment]
Oh I see. Looks like the `web-audio-api` library haven't been finished and not all effect on this libary could be used with it. For example the PingPongDelay's effect will need to use `AudioContext.createDelay` to create `DelayNode` but the `web-audio-api` doesn't have it.

But I think it could be possible if you spawn a headless browser with Puppeteer, so you can use this library to record inside the windowless browser and send it to the Node.js server. When using Puppeteer you just need [to navigate](https://github.com/puppeteer/puppeteer/#usage) the headless browser to your `index.html` that contain your `<script>`. You may also need to use non-headless options to debug/test if something went wrong, and also you will need to [override the permission](https://github.com/puppeteer/puppeteer/issues/3241) so it wouldn't ask for permission when want to use the Microphone inside of headless browser.

And also to reduce the latency or stream delay I think you can use [uWebSocket.js](https://github.com/uNetworking/uWebSockets.js) instead of Socket.io for Node.js.

**Comment by Tuner32** [comment]
Do you have example of uwebsocket.js? I tried 6 hours but I can't find way about json.stringify with data blob.

**Comment by Tuner32** [comment]
Do you know about way to receive nodejs and edit with webaudioapi in nodejs because I don't need any effect except pannernode to audio spatialization  and stream to browser. Do you know how can I recieve codec webm/opus?

**Comment by StefansArya** [comment]
Sorry I'm still busy maintaining some other project.
If you haven't familiar with uWebSocket.js for sending data then Socket.io should be your current choices.

For modifying the audio natively and create a streaming server I recommend to use library from different language like [C++](https://docs.juce.com/master/classdsp_1_1Panner.html), or [Golang](https://medium.com/@valentijnnieman_79984/how-to-build-an-audio-streaming-server-in-go-part-1-1676eed93021). Currently Node.js doesn't support PannerNode, and only Javascript on the Browser could support it because it has WebAudioAPI.

**Comment by Tuner32** [comment]
I good I can wait  a lot. I am really tank you to you about answer. I an try to make prototype whit socketio and with https://github.com/audiojs/web-audio-api this. If I am right, I think this is web audio api for nodejs, and I played example about this. But problem is I have no idea about How can I recive nodejs from sfmediastream on bowser and send again. Do you have any solution? or I have to made with c++ or python?

**Comment by StefansArya** [comment]
> How can I recive nodejs from sfmediastream on bowser and send again.

Hmm, do you mean send audio from Node.js into the browser, then apply the effect with SFMediaStream and then send the audio back into Node.js? or maybe, send the audio from the browser into Node.js and send the buffer again to the other browser?

> or I have to made with c++ or python?

Well, exploring is a good idea to find the a solution. Maybe you can find something that more suitable for your case. Usually Python have more libraries and easy to implement.

**Comment by Tuner32** [comment]
No I don't want edit on browser to browser. I want edit in nodejs with https://github.com/audiojs/web-audio-api this.How can I receive audio data and encode and send?

**Comment by StefansArya** [comment]
Sorry, but it's out of scope of this library.
SFMediaStream is supposed to work on browser, not Node.js because it doesn't have native WebAudio API.
From the official documentation it [doesn't mention that WebAudio API is compatible with Node.js](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API#browser_compatibility).

The [web-audio-api](https://github.com/audiojs/web-audio-api) library seems inactive since 4 years ago, and it haven't support some feature of browser's WebAudio API. Because you want to edit in Node.js and not in the browser, then this library is not your solution. I think I have mentioned that "this library is for browser because Node.js doesn't natively support WebAudio API" from [my previous comment](https://github.com/ScarletsFiction/SFMediaStream/issues/15#issuecomment-757097856). Please understand carefully about the limitation.

I'm closing this issue because it's getting invalid.

**Comment by Tuner32** [comment]
Ok..  I think I am wrong. I need to use browser to edit audio. But How can I recive ScarletsAudioStreamer and send  
 by ScarletsMediaPresenter?

**Comment by Tuner32** [comment]
I want to make demo first
