### ISSUE TITLE
Audio Connect multiple

### ISSUE THREAD

**Issue by Tuner32** [ScarletsFiction/SFMediaStream#18]
How can I connect multiple effect input node? From ScarletsAudioStreamer?

**Comment by StefansArya** [comment]
Of course, you can connect it like below:

`Input -> Effect1 -> Effect2 -> Destination`
```js
InputNode.connect(Effect1.input);
Effect1.output.connect(Effect2.input);
Effect2.output.connect(AudioContext.destination);
```

or parallely like this:

```
        --Effect1 --v
Input --|           |--> Destination
        --Effect2 --^
```

```js
InputNode.connect(Effect1.input);
InputNode.connect(Effect2.input);
Effect1.output.connect(AudioContext.destination);
Effect2.output.connect(AudioContext.destination);
```

Maybe you can also interested to try [Blackprint](https://blackprint.github.io/) for playing the WebAudio Effects.
But sorry if you found bugs, because it's pretty difficult to maintain multiple project alone 😅.

**Comment by Tuner32** [comment]
You are project is cool. It work well. Thank you . I sloved problem.
