### ISSUE TITLE
Audio Recoding on Firefox does not work

### ISSUE THREAD

**Issue by banstola** [ScarletsFiction/SFMediaStream#5]
I am using this library to broadcast audio to different subscriber on a prototype application. But recording from Firefox can not be broadcasted to client. It works fine on chrome meanwhile.

mimeType: audio/webm;codecs="opus"

**Comment by StefansArya** [comment]
Hi, I'm sorry because I don't have a solution for Firefox yet.
It just like Firefox's internal encoder itself, to fix it I may need to add a polyfill..
But unfortunately I don't have time to do that..

My current test:
Chrome: 74.0.3729.169
Firefox Quantum: 68.0

Chrome -> Firefox (Working)
Firefox -> Chrome (Not working)
Chrome <-> Opera GX (Working)

**Comment by banstola** [comment]
Hi, Thank you for your response. Is there any workaround that I could do with polyfill at my code?

**Comment by StefansArya** [comment]
Yes, we just need to replace the `window.MediaRecorder` with this [polyfill](https://github.com/kbumsik/opus-media-recorder#use-opus-media-recorder-only-when-a-browser-doesnt-support-it).
I haven't try it because I still at different workspace, but it maybe work.

The another one is [chris-rudmin/opus-recorder](https://github.com/chris-rudmin/opus-recorder), but I think we need to write extra code to make it work with this library.

**Comment by banstola** [comment]
Thank you for your help. I ended up not using the library instead running on a loop to start and stop recording every 5 seconds. This library is great btw. It gave me direction on how to approach the problem.
